branch-defaults:
  master:
    environment: deep-metal-demo
    group_suffix: null
global:
  application_name: deep-metal-demo
  branch: null
  default_ec2_keyname: deep-metal-eb
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
