name: Elastic Beanstalk Deployment
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Deploy to Elastic Beanstalk
      uses: nohmad/elastic-beanstalk-action@master
      with:
        sub-command: deploy
        environment: ${{ github.event.inputs.stage }}
        optional-args: '--nohang'
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
