name: Elastic Beanstalk Deployment
on:
  push:
    tags:
      - 'v*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1
      
    - name: Elastic Beanstalk Deployment
      uses: kumarshivam12/Aws-ElasticBeanstalk@v1.4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        EB-BUCKET-NAME: elasticbeanstalk-eu-north-1-774679440178
        APPLICATION-NAME: deep-metal-demo
        EB-ENV-NAME: deep-metal-demo
        AWS-REGION: eu-north-1
